In [29]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import pandas as pd
import requests, sys #to communicate with Ensembl servers
import json 
import numpy as np
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

newFrame=pd.read_csv('Table_EV3/Table_EV3.csv')

subFrame=newFrame.iloc[:,4:].copy()
# 
# 
subFrame = subFrame.replace('NA', np.nan, regex=True)

In [2]:
subFrame.head(5)

subFrame=subFrame.apply(pd.to_numeric)
mRNA_cols = [col for col in subFrame.columns if '_mRNA' in col]

PTR_cols = [col for col in subFrame.columns if '_PTR' in col]
protein_cols = [col for col in subFrame.columns if '_protein' in col]
PTRFrame =subFrame.loc[:,PTR_cols]
PTRFrame.head(5)

,Adrenal_mRNA,Appendices_mRNA,Brain_mRNA,Colon_mRNA,Duodenum_mRNA,Endometrium_mRNA,Esophagus_mRNA,Fallopiantube_mRNA,Fat_mRNA,Gallbladder_mRNA,...,Rectum_PTR,Salivarygland_PTR,Smallintestine_PTR,Smoothmuscle_PTR,Spleen_PTR,Stomach_PTR,Testis_PTR,Thyroid_PTR,Tonsil_PTR,Urinarybladder_PTR
0,NaN,1.073,NaN,NaN,NaN,NaN,NaN,1.054,NaN,NaN,...,NaN,7.718,NaN,NaN,7.313,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,1.971,2.324,NaN,NaN,NaN,NaN,1.569,...,5.147,NaN,5.202,NaN,NaN,5.8143,NaN,NaN,NaN,NaN
2,3.154,3.021,2.824,3.321,3.006,3.344,3.412,2.659,3.653,3.569,...,6.081,5.726,5.699,4.997,5.136,6.5349,5.82,6.06,5.675,5.8286
3,NaN,NaN,1.355,NaN,NaN,NaN,3.248,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.35,NaN,5.249,NaN
4,1.625,1.567,NaN,NaN,NaN,NaN,1.691,1.564,NaN,NaN,...,4.731,4.508,NaN,NaN,NaN,4.0613,4.832,NaN,NaN,4.243

,Adrenal_PTR,Appendices_PTR,Brain_PTR,Colon_PTR,Duodenum_PTR,Endometrium_PTR,Esophagus_PTR,Fallopiantube_PTR,Fat_PTR,Gallbladder_PTR,...,Rectum_PTR,Salivarygland_PTR,Smallintestine_PTR,Smoothmuscle_PTR,Spleen_PTR,Stomach_PTR,Testis_PTR,Thyroid_PTR,Tonsil_PTR,Urinarybladder_PTR
0,NaN,8.277,NaN,NaN,NaN,NaN,NaN,7.841,NaN,NaN,...,NaN,7.718,NaN,NaN,7.313,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,5.135,5.371,NaN,NaN,NaN,NaN,5.425,...,5.147,NaN,5.202,NaN,NaN,5.8143,NaN,NaN,NaN,NaN
2,6.290,6.328,5.948,5.811,6.068,5.383,5.881,6.119,6.41,5.828,...,6.081,5.726,5.699,4.997,5.136,6.5349,5.820,6.06,5.675,5.8286
3,NaN,NaN,3.995,NaN,NaN,NaN,4.129,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.350,NaN,5.249,NaN
4,3.843,4.601,NaN,NaN,NaN,NaN,4.013,3.683,NaN,NaN,...,4.731,4.508,NaN,NaN,NaN,4.0613,4.832,NaN,NaN,4.2430

pandas.core.frame.DataFrame

In [22]:
from Bio.Seq import Seq
from Bio.Alphabet import IUPAC
my_seq = Seq("GATCGATGGGCCTATATAGGATCGAAAATCGC", IUPAC.unambiguous_dna)

my_seq = "AUGGGAAGAAAAUCGCUGUACCUUCUGAUUGUGGGGAUCCUCAUAGCAUAUUAUAUUUAUACGCCUCUCCCAGAUAACGUUGAGGAGCCAUGGAGAAUGAUGUGGAUAAACGCACAUCUGAAAACUAUACAAAAUUUGGCUACAUUUGUGGAGCUCCUGGGACUUCACCAUUUUAUGGAUUCCUUUAAGGUUGUCGGGAGCUUUGAUGAAGUCCCACCAACCUCAGAUGAAAAUGUCACUGUGACUGAGACAAAAUUCAACAACAUUCUUGUUCGGGUAUAUGUGCCAAAGAGAAAGUCUGAAGCACUAAGAAGGGGGUUGUUUUACAUCCAUGGUGGAGGCUGGUGCGUGGGAAGUGCUGCUCUAAGUGGUUAUGACUUGCUGUCAAGAUGGACAGCAGACAGACUUGAUGCUGUCGUCGUAUCAACCAACUACAGAUUAGCACCUAAGUAUCAUUUCCCAAUUCAAUUUGAAGAUGUAUAUAAUGCCUUAAGGUGGUUCUUACGUAAAAAAGUUCUUGCAAAAUAUGGUGUGAACCCUGAGAGAAUCGGUAUUUCUGGAGAUAGUGCAGGAGGGAAUUUAGCUGCAGCAGUGACUCAACAGCUCCUUGAUGACCCAGAUGUCAAGAUCAAACUCAAGAUCCAGUCUUUAAUUUAUCCUGCCCUUCAGCCUCUUGAUGUAGAUUUACCGUCAUAUCAAGAAAAUUCAAAUUUUCUAUUUCUAUCCAAAUCACUCAUGGUCAGAUUCUGGAGUGAAUAUUUUACCACUGAUAGAUCACUUGAAAAAGCCAUGCUUUCCAGACAACAUGUACCUGUGGAAUCAAGUCAUCUCUUCAAAUUUGUUAAUUGGAGUUCCCUGCUCCCUGAGAGGUUUAUAAAAGGACAUGUUUAUAACAAUCCAAAUUAUGGCAGUUCUGAGCUGGCUAAAAAAUAUCCAGGGUUCCUAGAUGUGAGGGCAGCCCCUUUGUUGGCUGAUGACAACAAAUUACGUGGCUUACCCCUGACCUAUGUCAUCACCUGUCAAUAUGAUCUCUUAAGAGAUGAUGGACUCAUGUAUGUCACCCGACUUCGCAACACUGGGGUUCAGGUGACUCAUAACCAUGUUGAGGAUGGAUUCCAUGGAGCAUUUUCAUUUCUGGGACUUAAAAUUAGUCACAGACUUAUAAAUCAGUAUAUUGAGUGGCUAAAGGAAAAUCUAUAG"
def CodonTableFrequency (my_seq):
    unit=1/(len(my_seq)//3)
    CodonsDict = { 
    "UUU": 0, "UUC": 0, "UUA": 0, "UUG": 0, "CUU": 0, 
    "CUC": 0, "CUA": 0, "CUG": 0, "AUU": 0, "AUC": 0, 
    "AUA": 0, "AUG": 0, "GUU": 0, "GUC": 0, "GUA": 0, 
    "GUG": 0, "UAU": 0, "UAC": 0, "UAA": 0, "UAG": 0, 
    "CAU": 0, "CAC": 0, "CAA": 0, "CAG": 0, "AAU": 0, 
    "AAC": 0, "AAA": 0, "AAG": 0, "GAU": 0, "GAC": 0, 
    "GAA": 0, "GAG": 0, "UCU": 0, "UCC": 0, "UCA": 0, 
    "UCG": 0, "CCU": 0, "CCC": 0, "CCA": 0, "CCG": 0, 
    "ACU": 0, "ACC": 0, "ACA": 0, "ACG": 0, "GCU": 0, 
    "GCC": 0, "GCA": 0, "GCG": 0, "UGU": 0, "UGC": 0, 
    "UGA": 0, "UGG": 0, "CGU": 0, "CGC": 0, "CGA": 0, 
    "CGG": 0, "AGU": 0, "AGC": 0, "AGA": 0, "AGG": 0, 
    "GGU": 0, "GGC": 0, "GGA": 0, "GGG": 0} 
    list_nucleotides =[my_seq[i:i+3] for i in range(0, len(my_seq), 3)]
    NumberCodons=0     
    for nucleotide in list_nucleotides:
        if not nucleotide in CodonsDict:
            continue
            print("not counted")
        else:
            CodonsDict[nucleotide]+= unit
            NumberCodons+=1
    return CodonsDict

print(CodonTableFrequency(my_seq))

{'UUU': 0.032499999999999994, 'UUC': 0.0175, 'UUA': 0.0225, 'UUG': 0.0125, 'CUU': 0.032499999999999994, 'CUC': 0.024999999999999998, 'CUA': 0.0175, 'CUG': 0.0225, 'AUU': 0.02, 'AUC': 0.015000000000000001, 'AUA': 0.0125, 'AUG': 0.0175, 'GUU': 0.02, 'GUC': 0.0225, 'GUA': 0.0125, 'GUG': 0.024999999999999998, 'UAU': 0.045000000000000005, 'UAC': 0.0075, 'UAA': 0, 'UAG': 0.0025, 'CAU': 0.024999999999999998, 'CAC': 0.005, 'CAA': 0.015000000000000001, 'CAG': 0.0125, 'AAU': 0.027499999999999997, 'AAC': 0.024999999999999998, 'AAA': 0.0375, 'AAG': 0.0175, 'GAU': 0.045000000000000005, 'GAC': 0.01, 'GAA': 0.0225, 'GAG': 0.0225, 'UCU': 0.01, 'UCC': 0.01, 'UCA': 0.0225, 'UCG': 0.0025, 'CCU': 0.02, 'CCC': 0.0025, 'CCA': 0.0225, 'CCG': 0.0025, 'ACU': 0.0175, 'ACC': 0.015000000000000001, 'ACA': 0.0075, 'ACG': 0.0025, 'GCU': 0.0175, 'GCC': 0.01, 'GCA': 0.027499999999999997, 'GCG': 0, 'UGU': 0.0025, 'UGC': 0.0025, 'UGA': 0, 'UGG': 0.02, 'CGU': 0.005, 'CGC': 0.0025, 'CGA': 0.0025, 'CGG': 0.0025, 'AGU': 0.02, 'AGC': 0.0025, 'AGA': 0.032499999999999994, 'AGG': 0.01, 'GGU': 0.01, 'GGC': 0.0075, 'GGA': 0.027499999999999997, 'GGG': 0.015000000000000001}

In [23]:
len(my_seq)
len(my_seq)//3

1200

400

In [19]:

import pandas as pd
import requests, sys #to communicate with Ensembl servers
import json 

CDSFrame = pd.read_csv('Table_EV4/Table_EV4.csv') # Import the excel file and call it xls_file
CDSFrame.head(5)
output = pd.DataFrame()#empty df
# total_rows['ColumnID'] = total_rows['ColumnID'].astype(str)
for i in CDSFrame['CDS_Sequence']:
    codon=CodonTableFrequency(i)#use of CodontTable fonction that outputs a dictionary 
    output = output.append(codon, ignore_index=True)#append as rows with column the dictionary keys
print(output.head())
# df_merge_col = pd.merge(df, output, left_index=True, right_index=True)# use merge method, not join to add with respect to rows
# df_merge_col.to_csv('CodonTable.csv',index=False)#use this method to save to csv, traditinal format, better than excel

,GeneName,EnsemblGeneID,EnsemblTranscriptID,EnsemblProteinID,UTR5_Sequence,CDS_Sequence,UTR3_Sequence,ProteinSequence
0,A1BG,ENSG00000121410,ENST00000263100,ENSP00000263100,GGGCCUCAUUGCUGCAGACGCUCACCCCAGACACUCACUGCACCGG...,AUGUCCAUGCUCGUGGUCUUUCUCUUGCUGUGGGGUGUCACCUGGG...,UGCAGCCGCGGGCCCAGGGUGCUGUUGGUGUCCUCAGAAGUGCCGG...,MSMLVVFLLLWGVTWGPVTEAAIFYETQPSLWAESESLLKPLANVT...
1,A1CF,ENSG00000148584,ENST00000373993,ENSP00000363105,UGAGCAACCCUAAUUAACCUGAUUUUUUGCUGAUAAUCACUCUCA,AUGGAAUCAAAUCACAAAUCCGGGGAUGGAUUGAGCGGCACUCAGA...,AGAUGCUUUUUUAAAUUUAAGAAUAAGACACACAAAACUCUAUUAA...,MESNHKSGDGLSGTQKEAALRALVQRTGYSLVQENGQRKYGGPPPG...
2,A2M,ENSG00000175899,ENST00000318602,ENSP00000323929,GAAAAGCUUAUUAGCUGCUGUACGGUAAAAGUGAGCUCUUACGGGA...,AUGGGGAAGAACAAACUCCUUCAUCCAAGUCUGGUUCUUCUCCUCU...,AGACCACAAGGCUGAAAAGUGCUUUGCUGGAGUCCUGUUCUCAGAG...,MGKNKLLHPSLVLLLLVLLPTDASVSGKPQYMVLVPSLLHTETTEK...
3,A2ML1,ENSG00000166535,ENST00000299698,ENSP00000299698,GUCCACCACCUAACCUGGUGGUUACAGAAGGAGGAACACAGUCCUC...,AUGUGGGCUCAGCUCCUUCUAGGAAUGUUGGCCCUAUCACCAGCCA...,GGAUAGGAGCUGGAAACUCAAUUAGUCCUCUGUGACAUUUACUGGA...,MWAQLLLGMLALSPAIAEELPNYLVTLPARLNFPSVQKVCLDLSPG...
4,A4GALT,ENSG00000128274,ENST00000401850,ENSP00000384794,UGCACUUCUGUGCCUCAAUUUCCUCAUCUGUAGGGUGGGGGUGGUG...,AUGUCCAAGCCCCCCGACCUCCUGCUGCGGCUGCUCCGGGGCGCCC...,GGGGCCCGCCAGGUCACCUCCCCAACCUGCUCCUGAUGGGGCACUG...,MSKPPDLLLRLLRGAPRQRVCTLFIIGFKFTFFVSIMIYWHVVGEP...

        AAA       AAC       AAG       AAU       ACA       ACC       ACG  \
0  0.006048  0.018145  0.016129  0.004032  0.010081  0.030242  0.016129
1  0.042017  0.011765  0.020168  0.028571  0.015126  0.030252  0.001681
2  0.023051  0.020339  0.037288  0.023051  0.024407  0.021017  0.004746
3  0.019244  0.020619  0.034364  0.020619  0.017182  0.023368  0.006186
4  0.008475  0.033898  0.031073  0.002825  0.005650  0.025424  0.019774

        ACU       AGA       AGC  ...       UCG       UCU       UGA       UGC  \
0  0.006048  0.000000  0.030242  ...  0.006048  0.002016  0.002016  0.020161
1  0.015126  0.020168  0.008403  ...  0.001681  0.011765  0.001681  0.001681
2  0.018305  0.004746  0.015593  ...  0.002034  0.017627  0.000678  0.006780
3  0.022680  0.006186  0.016495  ...  0.006186  0.016495  0.000687  0.005498
4  0.008475  0.002825  0.011299  ...  0.005650  0.002825  0.002825  0.019774

        UGG       UGU       UUA       UUC       UUG       UUU
0  0.018145  0.000000  0.000000  0.026210  0.012097  0.012097
1  0.006723  0.006723  0.016807  0.015126  0.008403  0.016807
2  0.007458  0.010169  0.005424  0.024407  0.010847  0.017627
3  0.011684  0.011684  0.006873  0.026117  0.015120  0.019931
4  0.028249  0.002825  0.000000  0.053672  0.005650  0.005650

[5 rows x 64 columns]

In [20]:
output.iloc[35].sum()

0.9999999999999999

In [21]:
df_merge_col = pd.merge(newFrame, output, left_index=True, right_index=True)# use merge method, not join to add with respect to rows
df_merge_col.head(5)
df_merge_col.to_csv('CodonTable.csv',index=False)#use this method to save to csv, tra

,GeneName,EnsemblGeneID,EnsemblTranscriptID,EnsemblProteinID,Adrenal_mRNA,Appendices_mRNA,Brain_mRNA,Colon_mRNA,Duodenum_mRNA,Endometrium_mRNA,...,UCG,UCU,UGA,UGC,UGG,UGU,UUA,UUC,UUG,UUU
0,A1BG,ENSG00000121410,ENST00000263100,ENSP00000263100,NA,1.073,NA,NA,NA,NA,...,0.006048,0.002016,0.002016,0.020161,0.018145,0.000000,0.000000,0.026210,0.012097,0.012097
1,A1CF,ENSG00000148584,ENST00000373993,ENSP00000363105,NA,NA,NA,1.971,2.324,NA,...,0.001681,0.011765,0.001681,0.001681,0.006723,0.006723,0.016807,0.015126,0.008403,0.016807
2,A2M,ENSG00000175899,ENST00000318602,ENSP00000323929,3.154,3.021,2.824,3.321,3.006,3.344,...,0.002034,0.017627,0.000678,0.006780,0.007458,0.010169,0.005424,0.024407,0.010847,0.017627
3,A2ML1,ENSG00000166535,ENST00000299698,ENSP00000299698,NA,NA,1.355,NA,NA,NA,...,0.006186,0.016495,0.000687,0.005498,0.011684,0.011684,0.006873,0.026117,0.015120,0.019931
4,A4GALT,ENSG00000128274,ENST00000401850,ENSP00000384794,1.625,1.567,NA,NA,NA,NA,...,0.005650,0.002825,0.002825,0.019774,0.028249,0.002825,0.000000,0.053672,0.005650,0.005650

In [ ]:
frame =df_merge_col.sort_values('Adrenal_PTR',ascending=False).head(int(df_merge_col.shape[0]*.05))
type(frame)